backend/config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?

  post '/graphql', to: 'graphql#execute'

  root to: 'home#index'
  get 'home/check', to: 'home#check'

  resources :lans
  resources :tickets
  resources :ticket_options

  devise_for :users
end

backend/app/models/lan.rb
class Lan < ApplicationRecord
  has_many :tickets, dependent: :restrict_with_error

  scope :upcoming, -> { where('starts_at >= ?', Time.zone.now) }
  scope :current, -> { where('starts_at <= ? AND ends_at >= ?', Time.zone.now, Time.zone.now) }
  scope :current_or_upcoming, -> { where('ends_at >= ?', Time.zone.now) }

  def self.first_current_or_upcoming
    Lan.current_or_upcoming.order(starts_at: :asc).first
  end
end

backend/app/controllers/lans_controller.rb
class LansController < ApplicationController
  before_action :set_lan, only: %i[show edit update destroy]

  # GET /lans
  # GET /lans.json
  def index
    @lans = Lan.all
  end

  # GET /lans/1
  # GET /lans/1.json
  def show; end

  # GET /lans/new
  def new
    @lan = Lan.new
  end

  # GET /lans/1/edit
  def edit; end

  # POST /lans
  # POST /lans.json
  def create
    @lan = Lan.new(lan_params)

    respond_to do |format|
      if @lan.save
        format.html { redirect_to @lan, notice: 'Lan was successfully created.' }
        format.json { render :show, status: :created, location: @lan }
      else
        format.html { render :new }
        format.json { render json: @lan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lans/1
  # PATCH/PUT /lans/1.json
  def update
    respond_to do |format|
      if @lan.update(lan_params)
        format.html { redirect_to @lan, notice: 'Lan was successfully updated.' }
        format.json { render :show, status: :ok, location: @lan }
      else
        format.html { render :edit }
        format.json { render json: @lan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lans/1
  # DELETE /lans/1.json
  def destroy
    @lan.destroy
    respond_to do |format|
      format.html { redirect_to lans_url, notice: 'Lan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_lan
    @lan = Lan.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def lan_params
    params.require(:lan).permit(:name, :starts_at, :ends_at, :planned_seats, :description)
  end
end

backend/app/helpers/lans_helper.rb
module LansHelper
end

backend/app/views/lans/_form.html.erb
<%= form_with(model: lan, local: true) do |form| %>
  <% if lan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lan.errors.count, "error") %> prohibited this lan from being saved:</h2>

      <ul>
      <% lan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :lan_name %>
  </div>

  <div class="field">
    <%= form.label :starts_at %>
    <%= form.date_select :starts_at, id: :lan_starts_at %>
  </div>

  <div class="field">
    <%= form.label :ends_at %>
    <%= form.date_select :ends_at, id: :lan_ends_at %>
  </div>

  <div class="field">
    <%= form.label :planned_seats %>
    <%= form.number_field :planned_seats, id: :lan_planned_seats %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :lan_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/lans/edit.html.erb
<h1>Editing Lan</h1>

<%= render 'form', lan: @lan %>

<%= link_to 'Show', @lan %> |
<%= link_to 'Back', lans_path %>

backend/app/views/lans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Starts at</th>
      <th>Ends at</th>
      <th>Planned seats</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lans.each do |lan| %>
      <tr>
        <td><%= lan.name %></td>
        <td><%= lan.starts_at %></td>
        <td><%= lan.ends_at %></td>
        <td><%= lan.planned_seats %></td>
        <td><%= lan.description %></td>
        <td><%= link_to 'Show', lan %></td>
        <td><%= link_to 'Edit', edit_lan_path(lan) %></td>
        <td><%= link_to 'Destroy', lan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lan', new_lan_path %>

backend/app/views/lans/new.html.erb
<h1>New Lan</h1>

<%= render 'form', lan: @lan %>

<%= link_to 'Back', lans_path %>

backend/app/views/lans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lan.name %>
</p>

<p>
  <strong>Starts at:</strong>
  <%= @lan.starts_at %>
</p>

<p>
  <strong>Ends at:</strong>
  <%= @lan.ends_at %>
</p>

<p>
  <strong>Planned seats:</strong>
  <%= @lan.planned_seats %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lan.description %>
</p>

<p>
  <strong>Tickets:</strong>
  <%= link_to 'Tickets', tickets_path(ticket: {lan_id: @lan.id}) %>
</p>

<%= link_to 'Edit', edit_lan_path(@lan) %> |
<%= link_to 'Back', lans_path %>