backend/config/routes.rb
Rails.application.routes.draw do
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?

  post '/graphql', to: 'graphql#execute'

  root to: 'home#index'
  get 'home/check', to: 'home#check'

  resources :lans
  resources :tickets
  resources :ticket_options

  devise_for :users
end

backend/app/models/ticket_option.rb
class TicketOption < ApplicationRecord
  belongs_to :ticket
end

backend/app/controllers/ticket_options_controller.rb
class TicketOptionsController < ApplicationController
  before_action :set_ticket_option, only: %i[show edit update destroy]

  # GET /ticket_options
  # GET /ticket_options.json
  def index
    @ticket_options = TicketOption.all
  end

  # GET /ticket_options/1
  # GET /ticket_options/1.json
  def show; end

  # GET /ticket_options/new
  def new
    @ticket_option = TicketOption.new
  end

  # GET /ticket_options/1/edit
  def edit; end

  # POST /ticket_options
  # POST /ticket_options.json
  def create
    @ticket_option = TicketOption.new(ticket_option_params)

    respond_to do |format|
      if @ticket_option.save
        format.html { redirect_to @ticket_option, notice: 'Ticket option was successfully created.' }
        format.json { render :show, status: :created, location: @ticket_option }
      else
        format.html { render :new }
        format.json { render json: @ticket_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ticket_options/1
  # PATCH/PUT /ticket_options/1.json
  def update
    respond_to do |format|
      if @ticket_option.update(ticket_option_params)
        format.html { redirect_to @ticket_option, notice: 'Ticket option was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket_option }
      else
        format.html { render :edit }
        format.json { render json: @ticket_option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ticket_options/1
  # DELETE /ticket_options/1.json
  def destroy
    @ticket_option.destroy
    respond_to do |format|
      format.html { redirect_to ticket_options_url, notice: 'Ticket option was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ticket_option
    @ticket_option = TicketOption.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def ticket_option_params
    params.require(:ticket_option).permit(:name, :price, :ticket_id)
  end
end

backend/app/helpers/ticket_options_helper.rb
module TicketOptionsHelper
end

backend/app/views/ticket_options/_form.html.erb
<%= form_with(model: ticket_option, local: true) do |form| %>
  <% if ticket_option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticket_option.errors.count, "error") %> prohibited this ticket_option from being saved:</h2>

      <ul>
      <% ticket_option.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ticket_option_name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :ticket_option_price %>
  </div>

  <div class="field">
    <%= form.label :ticket_id %>
    <%= form.text_field :ticket_id, id: :ticket_option_ticket_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

backend/app/views/ticket_options/edit.html.erb
<h1>Editing Ticket Option</h1>

<%= render 'form', ticket_option: @ticket_option %>

<%= link_to 'Show', @ticket_option %> |
<%= link_to 'Back', ticket_options_path %>

backend/app/views/ticket_options/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ticket Options</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Ticket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ticket_options.each do |ticket_option| %>
      <tr>
        <td><%= ticket_option.name %></td>
        <td><%= ticket_option.price %></td>
        <td><%= ticket_option.ticket %></td>
        <td><%= link_to 'Show', ticket_option %></td>
        <td><%= link_to 'Edit', edit_ticket_option_path(ticket_option) %></td>
        <td><%= link_to 'Destroy', ticket_option, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket Option', new_ticket_option_path %>

backend/app/views/ticket_options/new.html.erb
<h1>New Ticket Option</h1>

<%= render 'form', ticket_option: @ticket_option %>

<%= link_to 'Back', ticket_options_path %>

backend/app/views/ticket_options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticket_option.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @ticket_option.price %>
</p>

<p>
  <strong>Ticket:</strong>
  <%= @ticket_option.ticket %>
</p>

<%= link_to 'Edit', edit_ticket_option_path(@ticket_option) %> |
<%= link_to 'Back', ticket_options_path %>